name: AutoRead Docker Image Push (勿动)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push auto-read
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: 14790897/auto-read:latest

      - name: Build and Push auto-like-user
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile-like-user
          push: true
          tags: 14790897/auto-like-user:latest
